### ISSUE TITLE
path problems (?) in preprocess_pdb.sh - without ligand

### ISSUE THREAD

**Issue by mjb84** [LPDI-EPFL/masif-neosurf#2]
Hi,
When trying to preprocess an entry without a ligand, it crashes on masif site step, failing to find nn_models.all_feat_31:

**./preprocess_pdb.sh example/1a7x.pdb 1A7X_A -o example/output/**

> ...
> Running masif site on /home/masif-neosurf/example/1a7x.pdb
> nn_models.all_feat_3l.custom_params
> Traceback (most recent call last):
>   File "/home/masif-neosurf/masif/source//masif_site/masif_site_predict.py", line 27, in <module>
>     custom_params = importlib.import_module(custom_params_file, package=None)
>   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'nn_models'

Adding catalogue with the said model to $PYTHONPATH helps with the issue, but it gets stuck on a similiar problem in next step.
Thanks for all the support and help
Michal

**Comment by arneschneuing** [comment]
Hi, thanks for raising this issue. I'm closing this as @knawel's fix (16c1cf8c68b33c94a9a38988bdf281088db6b633) should solve it. Feel free to re-open if you still run into problems.
